### ISSUE TITLE
unexpected EOF while looking for matching `"' when run runpilot2-wrapper.sh

### ISSUE THREAD

**Issue by a6350202** [ptrlv/adc#12]
Hello, 

After I executed runpilot2-wrapper.sh, I got this error:
```
/tmp/runpilot2-wrapper.sh: line 515: unexpected EOF while looking for matching `"'
/tmp/runpilot2-wrapper.sh: line 516: syntax error: unexpected end of file
``` 

I think https://github.com/ptrlv/adc/blob/master/runpilot2-wrapper.sh?fbclid=IwAR2Zp038Knr4u3T4esGKN80N-6t5WmU4TlZMISHfxakhUEv_z4rrQIGrEZg#L406
```
log "pandaIDs.out content:
                          ^
                          | ------  is missing `"`
```

is missing one quote. 
thanks!

**Comment by ptrlv** [comment]
Thanks!
